# Generated by Django 5.0.6 on 2024-07-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0003_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_lines',
            field=models.JSONField(default=list),
        ),
    ]
