# Generated by Django 5.0.6 on 2024-07-05 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0004_order_shipping_lines'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreparedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prepared_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webhook.order')),
            ],
        ),
    ]
