# Generated by Django 5.0.6 on 2024-07-05 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0005_preparedorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preparedorder',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webhook.order'),
        ),
    ]
