# Generated by Django 5.0.6 on 2024-07-06 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0007_order_status_delete_preparedorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.IntegerField(max_length=10, unique=True),
        ),
    ]
