# Generated by Django 5.0.6 on 2024-07-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0008_alter_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.IntegerField(unique=True),
        ),
    ]
